// app/layout.js
import "./globals.css";

export const metadata = {
  title: "LeatherFire Portfolio",
  description: "Generated by Yigitcan Ucar",
  icons: {
    icon: "/icons/utilities-terminal.svg", // Favicon dosyanızın yolu
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />

        {/* Önerilen: Preconnect linkleri */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />

        {/* Burada dilediğiniz fontları ekleyebilirsiniz. Örneğin Freeman ve Noto Sans Mono */}
        <link
          href="https://fonts.googleapis.com/css2?family=Freeman&family=Noto+Sans+Mono:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <div id="portal-root" />
      </body>
    </html>
  );
}
